
name: Release Node.js Package

on:
  release:
    types: [created]

jobs:
  lintAndTest:
    uses: ./.github/workflows/pr.yaml

  build:
    needs: lintAndTest
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://github.com/Fcmam5/eslint-plugin-todo-tickets/releases
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}